### ISSUE TITLE
Add a flag to indicate whether the input has changed since last optimization was run

### ISSUE THREAD

**Issue by MichaelPesce** [watertap-org/watertap-ui#120]

**Comment by dangunter** [comment]
More (any) details: Right now, when you do the following workflow:
- configure the flowsheet inputs
- solve the flowsheet
- view the outputs
- go back and change the flowsheet inputs
- (do NOT solve the flowsheet)
- view the outputs

There is no indication that the outputs came from the solve with the 1st (not the 2nd) set of input values. This could get confusing. The tasks therefore are:
1) Come up with a design for how to indicate this information
2) Implement this design in the UI

**Comment by MichaelPesce** [comment]
handled in #134
