### ISSUE TITLE
Launch the Electron window after React & FastAPI finish launching

### ISSUE THREAD

**Issue by elbashandy** [watertap-org/watertap-ui#3]
This proves to be challenging because there should be some sort of inter-process communication between the 3 processes for the apps to launch correctly (Electron, React, and FastAPI). Right now, Electron launches prematurely before React & FastAPI finish deploying.

**Comment by dangunter** [comment]
Doesn't Electron start the Python server?

**Comment by elbashandy** [comment]
It does but electron might launch the window before the Python server is ready to receive api calls.

**Comment by dangunter** [comment]
I think the best behavior would be to have a splash screen while Electron is waiting for the backend to be ready. e.g. see this article https://medium.com/red-buffer/how-to-create-a-splash-screen-for-electron-app-602b4da406d

**Comment by elbashandy** [comment]
Done!
