### ISSUE TITLE
Expose model configuration options in GUI

### ISSUE THREAD

**Issue by adam-a-a** [watertap-org/watertap-ui#85]
Based on some feedback from the NAWI Spring Meeting, one idea that came to mind was allowing for a drop-down box that lists configuration options for a particular model. For example: 

The nanofiltration model that we presented on --- there is a configuration option called `ConcentrationPolarizationType`, and you can choose to either include the effects of concentration polarization (`ConcentationPolarization.calculated`) or exclude them (`ConcentrationPolarization.none`) in your model. Right now, things are setup so that we build a specific flowsheet with configuration options that are selected by the model developer who is exporting that flowsheet to the GUI. For example, `ConcentrationPolarization.calculated` was selected for our nanofiltration example and that's what is run when we build/solve in the GUI.

However, if we could specify the config option from the GUI and then have the flowsheet built based on the selected config option, that would offer some nice flexibility. Would a feature like that be reasonable to request?

**Comment by dangunter** [comment]
Working on this in https://github.com/watertap-org/watertap/pull/1085 and https://github.com/watertap-org/watertap-ui/pull/90
